# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-10 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=100)),
                ('emp_email', models.CharField(max_length=100)),
                ('emp_dob', models.DateField()),
                ('emp_pass', models.CharField(max_length=100)),
            ],
        ),
    ]
